[package]
name = "lib_tricount"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
ordered-float = {version = "4.1", features = ["serde"]}
